services:
  postgres:
    image: postgres:16
    container_name: polymarket_algo_postgres
    environment:
      POSTGRES_USER: polyalgo
      POSTGRES_PASSWORD: polyalgo
      POSTGRES_DB: polyalgo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    container_name: polymarket_algo_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:

